[projects."/Users/gaurav/Script-BackUp"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/infra"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/Algogrit/algogrit.com"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/vyuha"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/thehour"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
