model = "gpt-5.6-terra"
model_reasoning_effort = "medium"
notify = ["/Users/gaurav/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
service_tier = "default"

[projects."/Users/gaurav/Script-BackUp"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/infra"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/Algogrit/algogrit.com"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/vyuha"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/thehour"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/infra/apps/vyom-ar"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/infra/apps/vyom-ar/landing-page"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/infra/apps/novel-signer"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/infra/apps/mirrorpad"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/astronomy-go"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/nayak"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/nayak-co"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/nayak/nayak-cl"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/nayak/nayak-co"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/Algogrit/value-investing-with-analysis"]
trust_level = "trusted"

[projects."/Users/gaurav/Downloads/Temp/2026/2026-06-auto-accountant"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/pdf-text-extractor"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/creator-kit"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/Presentations/presentation-demystifying-webrtc"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/Presentations/presentation-template"]
trust_level = "trusted"

[projects."/Users/gaurav/Developer/CMTech/Ramayan"]
trust_level = "trusted"

[tui]
status_line = ["model-with-reasoning", "context-remaining", "current-dir", "model-name", "context-used"]
single_key_approval = false

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[ui]
single_key_approval = false

[desktop]
appearanceTheme = "system"

[notice]
hide_rate_limit_model_nudge = true
