#!/bin/sh
git_command_to_run=$*

if [ $git_command_to_run = "help" ]; then
  echo "Runs the git command on the repositories within the current directory.
  Usage:
  	\$ git multi status
  	\$ git multi remote update"
  exit 0
fi

start_time=`date +%s`
base=$(pwd)

# save and change IFS 
NEWIFS=$'\n'
OLDIFS=$IFS
IFS=$NEWIFS

repository_list=($(find . -type d -maxdepth 2 -name '.git' | cut -d '/' -f 2))
repository_count=${#repository_list[@]}

echo "\033[1;33m$repository_count repositories found:\033[0m"
for (( i=0; i<${repository_count}; i++ ));
do
	echo "	${repository_list[$i]}"
done
echo ""

for (( i=0; i<${repository_count}; i++ ));
do
	cd "${repository_list[$i]}"
	echo "\033[1;33mOn $[ $i + 1 ] of $repository_count - \033[1;35m`basename $(PWD)`\r\033[0m"

	IFS=$OLDIFS

	git $git_command_to_run

	IFS=$NEWIFS

	cd $base
	echo ""
done

# Restore IFS
IFS=$OLDIFS

echo "\033[1;31mgit multi $git_command_to_run took $((`date +%s` - $start_time)) sec(s).\033[0m"
