#!/bin/sh
git clean -dfx
echo "Reflog commit count: `git reflog | wc -l`"
echo "Stash count: `git stash list | wc -l`"
git reflog expire --expire=now --all
git gc --prune=now
git fsck
git reset HEAD --hard
