#!/bin/sh

echo "Comamnds:
	new-commits	-	Updates the remote HEAD and show log of commits only in remote repo (git remote update && git log)
	pristine	-	Does a damn good job of cleaning the repository (WARNING: Removes .idea turd files)
	wash		-	Does a okay job of cleaning the repository

	multi		-	See 'git multi help'"
