#! /usr/bin/env sh

echo "Comamnds:
  pristine              - Hard cleans the repository (think fresh clone)
  wash                  - Cleans up the repository (Removes untracked directories, ignores entries in .gitignore)
  nuke                  - Removes the branch from local and also deletes from remote origin
  swamp                 - List the latest commit's timestamp for each remote branch
  ls-modified           - Lists all the modified files in the repo (or) the director(y|ies) specified
  ls-modified           - Lists all the untracked files in the repo (or) the director(y|ies) specified
  new-commits           - Show log of commits not yet pushed
  catchup               - Show log of commits only in remote repo

  multi                 - See 'git multi help'"
