#!/bin/sh
startt=`date +%s`
base=$(pwd)
folder_list=$(find . -type d -maxdepth 2 -name '.git')

folder_size=`echo $folder_list | wc -w`
count=0
echo '\n'
for repo_path in $folder_list
do
	let count+=1
	echo $repo_path
	cd $(echo $repo_path"/..")
	echo "\033[1;33mUpdating $count of $folder_size \r\033[0m";
	git pull --stat --progress
	cd $base
done

echo ""
echo "\033[1;33mUpdate completed in $((`date +%s` - $startt)) secs.\033[0m"
