#! /usr/bin/env sh

set -e

usage() {
  printf '%s\n' 'Usage: git nuke <branch>'
  printf '%s\n' ''
  printf '%s\n' 'Deletes the branch locally and on the origin remote.'
}

case "$1" in
  -h|--help) usage; exit 0 ;;
esac

if [ "$#" -ne 1 ] || [ -z "$1" ]; then
  usage >&2
  exit 2
fi

git branch -d "$1"
git push origin ":$1"

printf '\033[1;33mSuccessfully removed branch \033[1;35m%s\033[0m\n' "$1"
