#! /usr/bin/env bash

# Author: Gaurav Agarwal
# Inspired by https://github.com/livingston/shell-scripts/blob/master/gua.sh
# "Unix was not designed to stop its users from doing stupid things, as that would also stop them from doing clever things." – Doug Gwyn

git_args=("$@")

if [ $# -eq 0 ] || [ "$1" = "help" ]; then
  echo "Runs the git command on the repositories within the current directory.
  Usage:
  	\$ git multi status
  	\$ git multi remote update
  	\$ git multi pull --rebase
  	\$ git multi commit -m \"Commit message with spaces\""
  exit 0
fi

start_time=$(date +%s)
base=$(pwd)

function run_command {
  heading=$1
  shift
  count=$#
  printf '\033[1;33m%s %s found:\033[0m\n' "$count" "$heading"
  for repo in "$@"
  do
    echo "  $repo"
  done
  echo ""

  i=0
  for repo in "$@";
  do
    ((i += 1))
    cd "$repo"
    printf '\033[1;33mOn %s of %s - \033[1;35m%s\r\033[0m\n' "$i" "$count" "$(basename "$PWD")"

    git "${git_args[@]}"

    cd "$base"
    echo ""
  done
}

mapfile -t repositories < <(find . -maxdepth 2 -type d -name '.git' | cut -d '/' -f 2)
mapfile -t symlinks < <(find . -maxdepth 1 -type l | cut -d '/' -f 2)

run_command "repositories" "${repositories[@]}"
run_command "symlinks" "${symlinks[@]}"

printf '\033[1;31mgit multi %s took %s sec(s).\033[0m\n' "${git_args[*]}" "$(($(date +%s) - start_time))"
