#! /usr/bin/env sh

echo "Comamnds:
  add-all               - Stage changed files in the current repo and app repositories
  add-nw                -
  auto-push             -
  catchup               - Show log of commits only in remote repo
  commit-all            - Commit staged changes in the current repo and app repositories
  latest                -
  ls-conflicted         -
  ls-modified           - Lists all the modified files in the repo (or) the director(y|ies) specified
  ls-new                -
  ls-untracked          - Lists all the untracked files in the repo (or) the director(y|ies) specified
  merge-to              - Merge the current clean branch into a target branch and check it out
  multi                 - See 'git multi help'
    `git multi help`
  multi-sh              -
  new-commits           - Show log of commits not yet pushed
  nuke                  - Removes the branch from local and also deletes from remote origin
  pristine              - Hard cleans the repository (think fresh clone)
  pull-all              - Pull/rebase the current repo and app repositories
  push-all              - Push the current repo and app repositories
  swamp                 - List the latest commit's timestamp for each remote branch
  up                    -
  wash                  - Cleans up the repository (Removes untracked directories, ignores entries in .gitignore)"
